-- AlterTable
ALTER TABLE `Booking` ADD COLUMN `deadline` DATETIME(3) NULL,
    MODIFY `status` ENUM('SERVICE_REQUESTED', 'SERVICE_PROPOSAL_SENT', 'NEGOTIATING', 'CONFIRMED', 'DECLINED', 'CANCELED', 'IN_PROGRESS', 'IDLE', 'COMPLETED', 'AWAITING_PAYMENT', 'AWAITING_REVIEW', 'REVIEW_COMPLETED') NOT NULL DEFAULT 'SERVICE_REQUESTED';
