-- AlterTable
ALTER TABLE `PORTFOLIOS` ADD COLUMN `adminNotes` TEXT NULL,
    ADD COLUMN `reviewedAt` DATETIME(3) NULL,
    ADD COLUMN `reviewedById` INTEGER NULL,
    ADD COLUMN `revisionNotes` TEXT NULL,
    ADD COLUMN `revisionRequested` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `SERVICE_LISTINGS` ADD COLUMN `adminNotes` TEXT NULL,
    ADD COLUMN `reviewedAt` DATETIME(3) NULL,
    ADD COLUMN `reviewedById` INTEGER NULL,
    ADD COLUMN `revisionNotes` TEXT NULL,
    ADD COLUMN `revisionRequested` BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE `ADMIN_ACTIONS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `adminId` INTEGER NOT NULL,
    `action` ENUM('APPROVE_PORTFOLIO', 'DECLINE_PORTFOLIO', 'REQUEST_PORTFOLIO_REVISION', 'APPROVE_LISTING', 'DECLINE_LISTING', 'REQUEST_LISTING_REVISION', 'RESOLVE_REPORT', 'WARN_USER', 'SUSPEND_USER', 'DELETE_USER', 'RESTORE_USER', 'DELETE_CONTENT', 'RESTORE_CONTENT', 'CREATE_ADMIN', 'REMOVE_ADMIN', 'VIEW_MESSAGES') NOT NULL,
    `targetType` ENUM('PORTFOLIO', 'SERVICE_LISTING', 'REPORT', 'USER', 'MESSAGE', 'SERVICE_REQUEST', 'BOOKING', 'REVIEW', 'COMMENT') NOT NULL,
    `targetId` INTEGER NOT NULL,
    `reason` TEXT NULL,
    `details` TEXT NULL,
    `metadata` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `ADMIN_ACTIONS_adminId_idx`(`adminId`),
    INDEX `ADMIN_ACTIONS_targetType_targetId_idx`(`targetType`, `targetId`),
    INDEX `ADMIN_ACTIONS_createdAt_idx`(`createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_MODERATIONS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `moderatedBy` INTEGER NOT NULL,
    `action` ENUM('WARNING', 'TEMPORARY_SUSPENSION', 'PERMANENT_SUSPENSION', 'ACCOUNT_DELETION', 'CONTENT_REMOVAL') NOT NULL,
    `reason` TEXT NOT NULL,
    `startDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `endDate` DATETIME(3) NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `notes` TEXT NULL,

    INDEX `USER_MODERATIONS_userId_idx`(`userId`),
    INDEX `USER_MODERATIONS_moderatedBy_idx`(`moderatedBy`),
    INDEX `USER_MODERATIONS_isActive_idx`(`isActive`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CONTENT_FLAGS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `reportId` INTEGER NULL,
    `flaggedType` ENUM('PORTFOLIO', 'SERVICE_LISTING', 'REPORT', 'USER', 'MESSAGE', 'SERVICE_REQUEST', 'BOOKING', 'REVIEW', 'COMMENT') NOT NULL,
    `flaggedId` INTEGER NOT NULL,
    `flaggedBy` INTEGER NOT NULL,
    `reason` TEXT NOT NULL,
    `status` ENUM('PENDING', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED') NOT NULL DEFAULT 'PENDING',
    `reviewedBy` INTEGER NULL,
    `reviewedAt` DATETIME(3) NULL,
    `resolution` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `CONTENT_FLAGS_flaggedType_flaggedId_idx`(`flaggedType`, `flaggedId`),
    INDEX `CONTENT_FLAGS_flaggedBy_idx`(`flaggedBy`),
    INDEX `CONTENT_FLAGS_status_idx`(`status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE INDEX `PORTFOLIOS_status_idx` ON `PORTFOLIOS`(`status`);

-- CreateIndex
CREATE INDEX `PORTFOLIOS_reviewedById_idx` ON `PORTFOLIOS`(`reviewedById`);

-- CreateIndex
CREATE INDEX `SERVICE_LISTINGS_status_idx` ON `SERVICE_LISTINGS`(`status`);

-- CreateIndex
CREATE INDEX `SERVICE_LISTINGS_reviewedById_idx` ON `SERVICE_LISTINGS`(`reviewedById`);

-- AddForeignKey
ALTER TABLE `ADMIN_ACTIONS` ADD CONSTRAINT `ADMIN_ACTIONS_adminId_fkey` FOREIGN KEY (`adminId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_MODERATIONS` ADD CONSTRAINT `USER_MODERATIONS_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_MODERATIONS` ADD CONSTRAINT `USER_MODERATIONS_moderatedBy_fkey` FOREIGN KEY (`moderatedBy`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CONTENT_FLAGS` ADD CONSTRAINT `CONTENT_FLAGS_flaggedBy_fkey` FOREIGN KEY (`flaggedBy`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CONTENT_FLAGS` ADD CONSTRAINT `CONTENT_FLAGS_reviewedBy_fkey` FOREIGN KEY (`reviewedBy`) REFERENCES `USERS`(`userId`) ON DELETE SET NULL ON UPDATE CASCADE;
