-- CreateTable
CREATE TABLE `PROGRESS_UPDATES` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bookingId` INTEGER NOT NULL,
    `updaterId` INTEGER NOT NULL,
    `message` TEXT NULL,
    `imageUrl` TEXT NULL,
    `videoUrl` TEXT NULL,
    `fileUrl` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PROGRESS_UPDATES` ADD CONSTRAINT `PROGRESS_UPDATES_bookingId_fkey` FOREIGN KEY (`bookingId`) REFERENCES `Booking`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PROGRESS_UPDATES` ADD CONSTRAINT `PROGRESS_UPDATES_updaterId_fkey` FOREIGN KEY (`updaterId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;
