-- CreateTable
CREATE TABLE `USERS` (
    `userId` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `firstName` VARCHAR(191) NOT NULL,
    `middleName` VARCHAR(191) NULL,
    `lastName` VARCHAR(191) NOT NULL,
    `profilePicture` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `USERS_email_key`(`email`),
    PRIMARY KEY (`userId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ROLES` (
    `roleId` INTEGER NOT NULL AUTO_INCREMENT,
    `roleName` ENUM('client', 'resolver', 'admin') NOT NULL,

    UNIQUE INDEX `ROLES_roleName_key`(`roleName`),
    PRIMARY KEY (`roleId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_ROLES` (
    `userId` INTEGER NOT NULL,
    `roleId` INTEGER NOT NULL,

    PRIMARY KEY (`userId`, `roleId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CLIENT_PROFILES` (
    `clientProfileId` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `bio` VARCHAR(191) NULL,
    `trustRating` DOUBLE NOT NULL DEFAULT 0,

    UNIQUE INDEX `CLIENT_PROFILES_userId_key`(`userId`),
    PRIMARY KEY (`clientProfileId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RESOLVER_PROFILES` (
    `resolverProfileId` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `bio` VARCHAR(191) NULL,
    `skills` VARCHAR(191) NULL,
    `trustRating` DOUBLE NOT NULL DEFAULT 0,

    UNIQUE INDEX `RESOLVER_PROFILES_userId_key`(`userId`),
    PRIMARY KEY (`resolverProfileId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CATEGORIES` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `categoryName` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,

    UNIQUE INDEX `CATEGORIES_categoryName_key`(`categoryName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SERVICES` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `categoryId` INTEGER NOT NULL,
    `serviceName` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,

    UNIQUE INDEX `SERVICES_serviceName_categoryId_key`(`serviceName`, `categoryId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SERVICE_LISTINGS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `serviceId` INTEGER NOT NULL,
    `resolverId` INTEGER NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,
    `isFeatured` BOOLEAN NOT NULL DEFAULT false,
    `maxPrice` DECIMAL(10, 2) NULL,
    `minPrice` DECIMAL(10, 2) NULL,
    `status` ENUM('draft', 'on_review', 'approved', 'rejected') NOT NULL DEFAULT 'draft',
    `availabilityStatus` ENUM('available', 'busy', 'inactive') NULL,
    `location` ENUM('onsite', 'offsite') NULL,
    `serviceImage` TEXT NOT NULL,

    UNIQUE INDEX `SERVICE_LISTINGS_serviceId_resolverId_key`(`serviceId`, `resolverId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BOOKINGS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `clientId` INTEGER NOT NULL,
    `serviceListingId` INTEGER NOT NULL,
    `serviceRequestId` INTEGER NULL,
    `bookingDate` DATE NOT NULL,
    `totalPrice` DECIMAL(10, 2) NOT NULL,
    `paymentStatus` CHAR(50) NOT NULL,
    `paymentDue` DATE NOT NULL,

    UNIQUE INDEX `BOOKINGS_serviceRequestId_key`(`serviceRequestId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PAYMENTS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bookingId` INTEGER NOT NULL,
    `paymentAmount` DECIMAL(10, 2) NOT NULL,
    `paymentDate` DATE NOT NULL,
    `paymentMethod` VARCHAR(100) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SERVICE_REQUESTS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `clientId` INTEGER NOT NULL,
    `categoryId` INTEGER NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,
    `requestedDate` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `status` CHAR(50) NOT NULL,
    `minPrice` DECIMAL(10, 2) NULL,
    `maxPrice` DECIMAL(10, 2) NULL,
    `deadline` DATETIME(0) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `REPORTS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `reporterId` INTEGER NOT NULL,
    `reportedUserId` INTEGER NOT NULL,
    `reportTitle` VARCHAR(255) NOT NULL,
    `reportDescription` TEXT NULL,
    `reportDate` DATE NOT NULL,
    `resolution` TEXT NULL,
    `status` CHAR(50) NOT NULL,
    `adminId` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MESSAGES` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `senderId` INTEGER NOT NULL,
    `receiverId` INTEGER NOT NULL,
    `messageContent` TEXT NOT NULL,
    `sentDate` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `readStatus` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `COMMENTS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `parentCommentId` INTEGER NULL,
    `commenterId` INTEGER NOT NULL,
    `serviceRequestId` INTEGER NULL,
    `commentDate` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `role` VARCHAR(191) NOT NULL,
    `commentContent` TEXT NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `REVIEWS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `reviewerId` INTEGER NOT NULL,
    `reviewedUserId` INTEGER NOT NULL,
    `serviceListingId` INTEGER NOT NULL,
    `reviewText` TEXT NULL,
    `rating` INTEGER NOT NULL,
    `reviewDate` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PORTFOLIOS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `resolverId` INTEGER NOT NULL,
    `categoryId` INTEGER NOT NULL,
    `itemName` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,
    `status` ENUM('PENDING_APPROVAL', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING_APPROVAL',
    `uploadDate` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PORTFOLIO_FILES` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `portfolioId` INTEGER NOT NULL,
    `url` TEXT NOT NULL,
    `fileType` VARCHAR(191) NOT NULL,
    `order` INTEGER NOT NULL,
    `isThumbnail` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SERVICE_LISTING_PORTFOLIO_ITEMS` (
    `serviceListingId` INTEGER NOT NULL,
    `portfolioItemId` INTEGER NOT NULL,

    PRIMARY KEY (`serviceListingId`, `portfolioItemId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `USER_ROLES` ADD CONSTRAINT `USER_ROLES_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_ROLES` ADD CONSTRAINT `USER_ROLES_roleId_fkey` FOREIGN KEY (`roleId`) REFERENCES `ROLES`(`roleId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CLIENT_PROFILES` ADD CONSTRAINT `CLIENT_PROFILES_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESOLVER_PROFILES` ADD CONSTRAINT `RESOLVER_PROFILES_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SERVICES` ADD CONSTRAINT `SERVICES_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `CATEGORIES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SERVICE_LISTINGS` ADD CONSTRAINT `SERVICE_LISTINGS_serviceId_fkey` FOREIGN KEY (`serviceId`) REFERENCES `SERVICES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SERVICE_LISTINGS` ADD CONSTRAINT `SERVICE_LISTINGS_resolverId_fkey` FOREIGN KEY (`resolverId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BOOKINGS` ADD CONSTRAINT `BOOKINGS_clientId_fkey` FOREIGN KEY (`clientId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BOOKINGS` ADD CONSTRAINT `BOOKINGS_serviceListingId_fkey` FOREIGN KEY (`serviceListingId`) REFERENCES `SERVICE_LISTINGS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BOOKINGS` ADD CONSTRAINT `BOOKINGS_serviceRequestId_fkey` FOREIGN KEY (`serviceRequestId`) REFERENCES `SERVICE_REQUESTS`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PAYMENTS` ADD CONSTRAINT `PAYMENTS_bookingId_fkey` FOREIGN KEY (`bookingId`) REFERENCES `BOOKINGS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SERVICE_REQUESTS` ADD CONSTRAINT `SERVICE_REQUESTS_clientId_fkey` FOREIGN KEY (`clientId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SERVICE_REQUESTS` ADD CONSTRAINT `SERVICE_REQUESTS_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `CATEGORIES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REPORTS` ADD CONSTRAINT `REPORTS_reporterId_fkey` FOREIGN KEY (`reporterId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REPORTS` ADD CONSTRAINT `REPORTS_reportedUserId_fkey` FOREIGN KEY (`reportedUserId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REPORTS` ADD CONSTRAINT `REPORTS_adminId_fkey` FOREIGN KEY (`adminId`) REFERENCES `USERS`(`userId`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MESSAGES` ADD CONSTRAINT `MESSAGES_senderId_fkey` FOREIGN KEY (`senderId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MESSAGES` ADD CONSTRAINT `MESSAGES_receiverId_fkey` FOREIGN KEY (`receiverId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMMENTS` ADD CONSTRAINT `COMMENTS_commenterId_fkey` FOREIGN KEY (`commenterId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMMENTS` ADD CONSTRAINT `COMMENTS_parentCommentId_fkey` FOREIGN KEY (`parentCommentId`) REFERENCES `COMMENTS`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `COMMENTS` ADD CONSTRAINT `COMMENTS_serviceRequestId_fkey` FOREIGN KEY (`serviceRequestId`) REFERENCES `SERVICE_REQUESTS`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REVIEWS` ADD CONSTRAINT `REVIEWS_reviewerId_fkey` FOREIGN KEY (`reviewerId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REVIEWS` ADD CONSTRAINT `REVIEWS_reviewedUserId_fkey` FOREIGN KEY (`reviewedUserId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `REVIEWS` ADD CONSTRAINT `REVIEWS_serviceListingId_fkey` FOREIGN KEY (`serviceListingId`) REFERENCES `SERVICE_LISTINGS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PORTFOLIOS` ADD CONSTRAINT `PORTFOLIOS_resolverId_fkey` FOREIGN KEY (`resolverId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PORTFOLIOS` ADD CONSTRAINT `PORTFOLIOS_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `CATEGORIES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PORTFOLIO_FILES` ADD CONSTRAINT `PORTFOLIO_FILES_portfolioId_fkey` FOREIGN KEY (`portfolioId`) REFERENCES `PORTFOLIOS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SERVICE_LISTING_PORTFOLIO_ITEMS` ADD CONSTRAINT `SERVICE_LISTING_PORTFOLIO_ITEMS_serviceListingId_fkey` FOREIGN KEY (`serviceListingId`) REFERENCES `SERVICE_LISTINGS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SERVICE_LISTING_PORTFOLIO_ITEMS` ADD CONSTRAINT `SERVICE_LISTING_PORTFOLIO_ITEMS_portfolioItemId_fkey` FOREIGN KEY (`portfolioItemId`) REFERENCES `PORTFOLIOS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
