-- AlterTable
ALTER TABLE `CLIENT_PROFILES` ADD COLUMN `cancellations` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `completedBookings` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `reviewsGiven` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `reviewsReceived` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `totalBookings` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `trustScore` DOUBLE NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `RESOLVER_PROFILES` ADD COLUMN `approvedPortfolios` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `cancellations` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `completedBookings` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `negativeReviews` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `neutralReviews` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `positiveReviews` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `reviewsGiven` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `reviewsReceivedCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `totalBookings` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `totalStarsReceived` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `trustScore` DOUBLE NOT NULL DEFAULT 0;
