-- AlterTable
ALTER TABLE `BOOKING_CHANGE_REQUESTS` ADD COLUMN `newStartDate` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `BOOKING_PROPOSALS` ADD COLUMN `startDate` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `Booking` ADD COLUMN `startDate` DATETIME(3) NULL;
