-- AlterTable
ALTER TABLE `PROGRESS_UPDATES` MODIFY `status` ENUM('AWAITING_START', 'IN_PROGRESS', 'IDLE', 'CANCELED', 'COMPLETED', 'AWAITING_REVIEW', 'REVIEW_COMPLETED', 'PAYMENT_COMPLETED') NOT NULL DEFAULT 'AWAITING_START';
