-- AddForeignKey
ALTER TABLE `CONVERSATIONS` ADD CONSTRAINT `CONVERSATIONS_listingId_fkey` FOREIGN KEY (`listingId`) REFERENCES `SERVICE_LISTINGS`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CONVERSATIONS` ADD CONSTRAINT `CONVERSATIONS_requestId_fkey` FOREIGN KEY (`requestId`) REFERENCES `SERVICE_REQUESTS`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
