-- AlterTable
ALTER TABLE `Booking` ADD COLUMN `bookingCompletedAt` DATETIME(3) NULL,
    ADD COLUMN `clientBookingAcknowledged` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `hasClientReview` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasResolverReview` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `paymentCompletedAt` DATETIME(3) NULL,
    ADD COLUMN `resolverBookingAcknowledged` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `reviewPeriodEndsAt` DATETIME(3) NULL,
    ADD COLUMN `reviewPeriodStartedAt` DATETIME(3) NULL,
    MODIFY `status` ENUM('SERVICE_REQUESTED', 'SERVICE_PROPOSAL_SENT', 'NEGOTIATING', 'CONFIRMED', 'DECLINED', 'CANCELED', 'IN_PROGRESS', 'IDLE', 'WORK_COMPLETED', 'PAYMENT_COMPLETED', 'BOOKING_COMPLETED', 'AWAITING_REVIEW', 'REVIEW_COMPLETED', 'AWAITING_PAYMENT', 'COMPLETED') NOT NULL DEFAULT 'SERVICE_REQUESTED';
