-- CreateTable
CREATE TABLE `BOOKING_CHANGE_REQUESTS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bookingId` INTEGER NOT NULL,
    `requesterId` INTEGER NOT NULL,
    `type` ENUM('CANCELLATION', 'ALTERATION') NOT NULL,
    `reason` TEXT NULL,
    `newPrice` DECIMAL(10, 2) NULL,
    `newDeadline` DATETIME(3) NULL,
    `status` ENUM('PENDING', 'APPROVED', 'DECLINED') NOT NULL DEFAULT 'PENDING',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `BOOKING_CHANGE_REQUESTS` ADD CONSTRAINT `BOOKING_CHANGE_REQUESTS_bookingId_fkey` FOREIGN KEY (`bookingId`) REFERENCES `Booking`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BOOKING_CHANGE_REQUESTS` ADD CONSTRAINT `BOOKING_CHANGE_REQUESTS_requesterId_fkey` FOREIGN KEY (`requesterId`) REFERENCES `USERS`(`userId`) ON DELETE RESTRICT ON UPDATE CASCADE;
